name: Shared - Run specs

on:
  workflow_call:
    secrets:
      LAMBDATEST_USER:
        required: true
      LAMBDATEST_KEY:
        required: true

jobs:
  run-specs:
    name: Build packages & run tests
    runs-on: ubuntu-latest
    env:
      DEFAULT_DEVICE: android
      DEFAULT_TYPE: regression
      LAMBDATEST_USER: ${{ secrets.LAMBDATEST_USER }}
      LAMBDATEST_KEY: ${{ secrets.LAMBDATEST_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=16.0.0"

      - name: Install all packages
        if: always()
        run: npm install

      - name: LambdaTest - run "${{ github.event.inputs.test-type }}" tests, on "${{ github.event.inputs.environment }}" env, on "${{ github.event.inputs.device }}" device
        if: always()
        run: |
          export LAMBDATEST_USER=${{ secrets.LAMBDATEST_USER }}
          export LAMBDATEST_KEY=${{ secrets.LAMBDATEST_KEY }}
          export TEST_TYPE=${{ github.event.inputs.test-type }}
          npx wdio config/wdio.lt.${{ github.event.inputs.device }}.${{ github.event.inputs.environment }}.conf.js
